# Generated by Django 4.0.1 on 2022-01-24 17:32

import datetime
import django.core.serializers.json
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 17, 32, 50, 553686, tzinfo=utc), null=True)),
                ('user', models.CharField(max_length=64)),
            ],
        ),
    ]
