# Generated by Django 4.0.1 on 2022-01-17 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 51, 35, 188346, tzinfo=utc), null=True),
        ),
    ]
