# Generated by Django 4.0.1 on 2022-01-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_completed_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(blank=True, default='2022-01-17T11: 14: 29.686934Z'),
        ),
    ]
